### ISSUE TITLE
Ms VISIO AUTOMATION

### ISSUE THREAD

**Issue by sumankrsh** [vesellov/visio2python#1]
Hello need one help , could please guide me how to automate MS Visio diagrams with help of python. There is an excel file with all the details of data which we used to do manually input inside MS Visio diagrams. so, the goal is that we will update the excel file only and Python will run and put all the data in the designated pre-defined diagrams and give us the output in a MS Visio format , so that we can format that if necessary with formatting issues.
If needed i can setup some time with you and we can discuss

Thank you

**Comment by vesellov** [comment]
This project is intended for different purposes - it is not for working with Excel diagrams but with MS Visio diagrams. Also we are not using Python here to "extract" data from MS Visio, but we use MS Visual Basic application to do that first and later Python scripts are making extra "formatting" of the extracted data. I am sorry, @Smukherjee80 , but it is clear to me that your question is not related to the `visio2python` project anyhow.
